language: swift

osx_image: xcode9.2

script:
  - xcodebuild -project TryTDD.xcodeproj -scheme TryTDD -sdk iphonesimulator
  - xcodebuild test -project TryTDD.xcodeproj -scheme TryTDDTests -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3'
