language: swift

osx_image: xcode9.3

before_install:
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  # - xcodebuild -project TryTDD.xcodeproj -scheme TryTDD -sdk iphonesimulator | xcpretty
  - xcodebuild clean test -project TryTDD.xcodeproj -scheme TryTDDTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' -configuration Debug -enableCodeCoverage YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet | xcpretty


after_success:
    - bash <(curl -s https://codecov.io/bash)

