language: swift

osx_image: xcode9.3

before_install:
  - xctool --version
  - xcodebuild -versoin
  - xcodebuild -showsdks
  - brew install xctool

script:
  - xcodebuild -project TryTDD.xcodeproj -scheme TryTDD -sdk iphonesimulator
  - xctool run-tests -project TryTDD.xcodeproj -scheme TryTDDTests -sdk iphonesimulator
