language: swift

osx_image: xcode9.3

script:
  - xcodebuild -project TryTDD.xcodeproj -scheme TryTDD -sdk iphonesimulator
  - xctool run-tests -project TryTDD.xcodeproj -scheme TryTDDTests -sdk iphonesimulator
